name: decoupled-dev
proxy:
  nginx:
    - cms.decoupled.lndo.site
  nodejs:
    - decoupled.lndo.site

services:
  cms:
    type: php:7.2
    via: nginx
    config:
      server: config/nginx/site.conf
    ssl: true
    webroot: backend/web
    xdebug: false
    overrides:
      services:
        environment:
          DB_HOST: mariadb
          DB_USER: cms
          DB_PASSWORD: cms
          DB_NAME: cms
          DB_PORT: 3306
    build:
      - "composer --ansi --working-dir=/app/backend install"
  mariadb:
    type: mariadb:10.3
    portforward: true
    creds:
      user: cms
      password: cms
      database: cms
  nodejs:
    type: node:8.9
    ssl: true
    build:
      - "cd frontend && yarn install"
    overrides:
      services:
        ports: [3333:3333]
tooling:
  composer:
    service: cms
    cmd:
      - "composer --ansi --working-dir=/app/backend"
  drush:
    service: cms
    cmd:
      - "/app/backend/vendor/drush/drush/drush --root=/app/backend/web"
  node:
    service: nodejs
  npm:
    service: nodejs
    cmd:
      - "npm --cwd=/app/frontend"
  yarn:
    service: nodejs
    cmd:
      - "yarn --cwd=/app/frontend"

events:
  post-start:
    - cms: "cp $LANDO_MOUNT/config/drupal/lando.settings.php $LANDO_MOUNT/backend/web/sites/default/settings.php"
    - cms: "cp $LANDO_MOUNT/backend/web/sites/example.settings.local.php $LANDO_MOUNT/backend/web/sites/default/settings.local.php"

